name: Build and Test

# See https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-test:
    name: Build and Test Web and Electron Apps
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Install Node.js and NPM
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 10
          cache: npm

      - name: Show Environment Info
        run: npm -v
      
      - name: Install dependencies
        run: npm ci

      - name: Build web app
        run: npx gulp build --platform=browser
      
      - name: Test web app
        run: npm run do scripts/test

      - name: Build Electron app
        run: npm run do src/electron/build
