name: Test

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:
  setup:
    name: Setup
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ matrix.os }};node_modules;${{ hashFiles('package-lock.json' )}}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --prefer-offline

      - name: Sanitize Dependency Permissions for Cache
        if: steps.cache.outputs.cache-hit != 'true'
        run: chmod -R --verbose 777 ./node_modules

  web-app:
    name: Web App
    runs-on: ${{ matrix.os }}
    needs: setup
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ matrix.os }};node_modules;${{ hashFiles('package-lock.json' )}}
      
      - name: Build
        run: npx gulp build --platform=browser
      
      - name: Test
        run: npm run do scripts/test

  electron:
    name: Electron
    runs-on: ${{ matrix.os }}
    needs: setup
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ matrix.os }};node_modules;${{ hashFiles('package-lock.json' )}}

      - name: Build
        run: npm run do src/electron/build
